# Endpoints

ROOT_ENDPOINT = "/estimate"

# ESTIMATE_ENDPOINT = "/estimate/generic"
ESTIMATE_ENDPOINT = ROOT_ENDPOINT
ESTIMATE_OPENAI_ENDPOINT = f"{ROOT_ENDPOINT}/openai"
ESTIMATE_OPENAI_STREAM_ENDPOINT = f"{ROOT_ENDPOINT}/openai/stream"
ESTIMATE_ANTHROPIC_ENDPOINT = f"{ROOT_ENDPOINT}/anthropic"

# OpenAI Configuration

OPENAI_MODEL_DEFAULT = "gpt-4o-mini"

# Anthropic Configuration

ANTHROPIC_MODEL_DEFAULT = "claude-haiku-4-5-20251001"
ANTHROPIC_MAX_TOKENS_DEFAULT = 4096
