import pytest
from pydantic import ValidationError

from app.responses.estimate_llmwrapper_responses import EstimationLLMWrapperResponse
from tests.units.app.responses.estimate_response_factory import (
    EstimateLLMWrapperResponseFactory,
)


@pytest.mark.parametrize(
    "overrides",
    [
        {"text": None},
        {"prompt_version": None},
    ],
)
def test_estimate_llmwrapper_response_rejects_invalid_required_fields(overrides):
    with pytest.raises(ValidationError):
        EstimateLLMWrapperResponseFactory.build(**overrides)


def test_estimate_llmwrapper_response_rejects_extra_fields():
    with pytest.raises(ValidationError):
        EstimateLLMWrapperResponseFactory.build(unexpected="extra")


def test_estimate_llmwrapper_response_is_created_from_factory_defaults():
    response = EstimateLLMWrapperResponseFactory.build()

    assert isinstance(response, EstimationLLMWrapperResponse)
    assert response.text == EstimateLLMWrapperResponseFactory.DEFAULT_TEXT
    assert response.prompt_version == EstimateLLMWrapperResponseFactory.DEFAULT_PROMPT_VERSION


def test_estimate_llmwrapper_response_is_created_with_custom_values():
    response = EstimateLLMWrapperResponseFactory.build(
        text="Estimate generated by the wrapper.",
        prompt_version="v2",
    )

    assert response.text == "Estimate generated by the wrapper."
    assert response.prompt_version == "v2"
