import pytest
from pydantic import ValidationError

from app.responses.estimate_llmwrapper_responses import EstimationLLMWrapperResponse
from tests.units.app.responses.estimate_response_factory import (
    EstimateLLMWrapperResponseFactory,
)

INVALID_REQUIRED_FIELD_OVERRIDES = [
    {"text": None},
    {"prompt_version": None},
]


def assert_response_is_invalid(**overrides) -> None:
    with pytest.raises(ValidationError):
        EstimateLLMWrapperResponseFactory.build(**overrides)


@pytest.mark.parametrize("overrides", INVALID_REQUIRED_FIELD_OVERRIDES)
def test_estimate_llmwrapper_response_rejects_invalid_required_fields(overrides):
    assert_response_is_invalid(**overrides)


def test_estimate_llmwrapper_response_rejects_extra_fields():
    assert_response_is_invalid(unexpected="extra")


def test_estimate_llmwrapper_response_is_created_from_factory_defaults():
    response = EstimateLLMWrapperResponseFactory.build()

    assert isinstance(response, EstimationLLMWrapperResponse)
    assert response.text == EstimateLLMWrapperResponseFactory.DEFAULT_TEXT
    assert response.prompt_version == EstimateLLMWrapperResponseFactory.DEFAULT_PROMPT_VERSION


def test_estimate_llmwrapper_response_is_created_with_custom_values():
    response = EstimateLLMWrapperResponseFactory.build(
        text="Estimate generated by the wrapper.",
        prompt_version="v2",
    )

    assert response.text == "Estimate generated by the wrapper."
    assert response.prompt_version == "v2"
